# Generated by Django 2.2.6 on 2019-11-26 16:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='learning',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
