# Generated by Django 2.2.6 on 2019-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191126_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='url',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
