# Generated by Django 2.2.6 on 2019-11-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_learning_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='url',
            new_name='_url',
        ),
    ]
