# Generated by Django 2.2.6 on 2019-11-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191126_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='_url',
            new_name='url',
        ),
    ]
