# Generated by Django 2.2.6 on 2019-11-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191126_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='url',
            new_name='course_url',
        ),
    ]
