# Generated by Django 2.2.6 on 2019-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191126_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(choices=[('M', 'Mr'), ('Ms', 'Mrs'), ('Dr', 'Doctor')], default='M', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
